os:
  - windows
language: node_js
node_js:
  - 10
before_script:
  - git config --global user.name "webpro"
  - git config --global user.email "lars@webpro.nl"
  - set PATH="%PATH%;C:\Program Files\Git\cmd\"
cache: npm
